### ISSUE TITLE
Is this project still being developed?

### ISSUE THREAD

**Issue by AngelRealms** [ajxs/jsFO#36]
I like the idea of this project but the last commit to master was 2 years ago so I am just wondering if this project has been abandoned.

**Comment by ajxs** [comment]
It's not currently under active development. I do plan to revisit the idea at some point, but I'm not sure how much of the codebase ( if any ) I'd reuse when that happens.
I actually checked the repo out two days ago by chance to clean it up and get it working again, so I'll be pushing some new commits very soon.

I started this project originally about 6 years ago. Since then there's been an enormous amount of changes in the Javascript ecosystem, first Node.js became huge, ES6 became widely adopted, and then WebAssembly was created. Many design decisions were made around problems that these technologies addressed.

If/when I plan to revisit the idea I would make very different decisions. First of all, I'd probably use another language compiled to a WebAssembly target.
One bad design decision I made was to use Python scripts to interpret the Fallout .dat files and encode their contents in a JSON-based format that could be easily interpreted by the browser. This was a poor decision all-round. The File API was not as well developed at that point in time, and I wanted to avoid requiring any user interaction to launch the demo. If I were to revisit the idea today I would use the File API to request a .dat file be loaded into the browser by 'drag+drop', and then interpret the binary format in the browser. It would be memory heavy, but much cleaner code.

If you, or anyone else, wanted to work on the project as it exists now in any capacity I would be glad to assist.

**Comment by darkf** [comment]
Even if not, there are other reimplementation projects:

[DarkFO](https://github.com/darkf/darkfo) (my own, also uses Web stuff)

Falltergeist in C++

[Vault13](https://github.com/pingw33n/vault13) (in Rust)

They're all a bit slow, as you might expect from large volunteer projects.

(Off-topic: Hey @ajxs, long time no see! Hope you're doing well.)

**Comment by ajxs** [comment]
I'm going great, thank you! Hope you're doing well also!

Thanks for mentioning those @darkf! There's also many other projects with the same goal, most of which are more complete re-implementations.
I'm almost a bit shocked the real source hasn't surfaced by now! haha
